### ISSUE TITLE
Notchecked

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chubakur/wizards-magic2#12]
```
strange console output "Notchecked!Notchecked!......................."
My cards
Apostate, Ice Guard, Satyr

Computer plays with Ghosts
```

Original issue reported on code.google.com by `chubakur@gmail.com` on 12 Jan 2014 at 9:36

**Comment by sandrobonazzola** [comment]
Can't reproduce this on my system:
python3-pygame-1.9.1-19.fc23.20150926.x86_64
pygame-1.9.1-19.fc23.20150926.x86_64
SDL-1.2.15-20.fc23.x86_64
SDL2-2.0.3-7.fc23.x86_64

**Comment by sandrobonazzola** [comment]
@chubakur I think you can close this one
